language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"

before_install:
  - npm install -g npm@latest
  - npm install -g grunt-cli

#travis build  speed up
sudo: false
cache:
  directories:
    - node_modules
